run:
  go: "1.22"
  timeout: 3m

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - revive
    - bodyclose
    - gocritic
    - misspell
    - unconvert
    - whitespace
    - tenv
    - makezero

linters-settings:
  revive:
    rules:
      - name: exported
        arguments:
          - disableStutteringCheck
      - name: blank-imports
      - name: context-as-argument
      - name: error-return
      - name: error-strings
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unused-parameter
      - name: unreachable-code
      - name: redefines-builtin-id
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - whyNoLint
  misspell:
    locale: US

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - unused
    - path: convert\.go
      linters:
        - gocritic
  max-issues-per-linter: 0
  max-same-issues: 0
